http:
  host: 'localhost'
  port: 3030

database:
  url: 'localhost'
  port: 5432
  name: 'yaml-db'
  another: 'value'
  props:
    first: 'first-val'
    second: 'second-val'
    more-nested:
      first: 'first-val'
      second: 'second-val'